use_frameworks!

platform :ios, '8.0'

target 'DjTestFramework8_Example' do
  pod 'DjTestFramework8', :path => '../'

  target 'DjTestFramework8_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
